#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kdegraphics-mobipocket
Version  : 23.04.0
Release  : 52
URL      : https://download.kde.org/stable/release-service/23.04.0/src/kdegraphics-mobipocket-23.04.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/23.04.0/src/kdegraphics-mobipocket-23.04.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/23.04.0/src/kdegraphics-mobipocket-23.04.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kdegraphics-mobipocket-lib = %{version}-%{release}
Requires: kdegraphics-mobipocket-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the kdegraphics-mobipocket package.
Group: Development
Requires: kdegraphics-mobipocket-lib = %{version}-%{release}
Provides: kdegraphics-mobipocket-devel = %{version}-%{release}
Requires: kdegraphics-mobipocket = %{version}-%{release}

%description dev
dev components for the kdegraphics-mobipocket package.


%package lib
Summary: lib components for the kdegraphics-mobipocket package.
Group: Libraries
Requires: kdegraphics-mobipocket-license = %{version}-%{release}

%description lib
lib components for the kdegraphics-mobipocket package.


%package license
Summary: license components for the kdegraphics-mobipocket package.
Group: Default

%description license
license components for the kdegraphics-mobipocket package.


%prep
%setup -q -n kdegraphics-mobipocket-23.04.0
cd %{_builddir}/kdegraphics-mobipocket-23.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682093236
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1682093236
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdegraphics-mobipocket
cp %{_builddir}/kdegraphics-mobipocket-%{version}/COPYING %{buildroot}/usr/share/package-licenses/kdegraphics-mobipocket/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QMobipocket/qmobipocket/mobipocket.h
/usr/include/QMobipocket/qmobipocket/qfilestream.h
/usr/include/QMobipocket/qmobipocket/qmobipocket_export.h
/usr/include/QMobipocket/qmobipocket_version.h
/usr/lib64/cmake/QMobipocket/QMobipocketConfig.cmake
/usr/lib64/cmake/QMobipocket/QMobipocketConfigVersion.cmake
/usr/lib64/cmake/QMobipocket/QMobipocketTargets-relwithdebinfo.cmake
/usr/lib64/cmake/QMobipocket/QMobipocketTargets.cmake
/usr/lib64/libqmobipocket.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqmobipocket.so.2
/usr/lib64/libqmobipocket.so.2.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdegraphics-mobipocket/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
